server:
  port: 8080

spring:
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.felton.mybatismapper.domain.entity
#mapper:
#  mappers: com.felton.mybatismapper.baseDao.IBaseDao
#  identity: MYSQL

global:
  log-dir: log/