spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
pagehelper:
#  数据库类型
  helper-dialect: mysql
#  查询合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
# 为了支持startPage(Object params)方法，增加了该参数来配置参数映射
  params: cpageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
#  支持mapper接口参数传递分页参数
  support-methods-arguments: true
#  pagesize=0 表内容全部查询
  page-size-zero: true



